/**
 * @file crypto.ts
 * @description Provides symmetric encryption and decryption utilities for sensitive data.
 * @architecture Used across the application to secure tokens and credentials before persisting to the database.
 */
import crypto from "crypto";

const ALGORITHM = "aes-256-gcm";
const IV_LENGTH = 16;
const SALT_LENGTH = 64;
const TAG_LENGTH = 16;
const KEY_LENGTH = 32;

/**
 * @desc Derives a cryptographic key from a password and salt using scrypt.
 * @param {string} password - The base password or secret.
 * @param {Buffer} salt - The salt buffer.
 * @returns {Buffer} The derived key buffer.
 */
function getKey(password: string, salt: Buffer): Buffer {
  return crypto.scryptSync(password, salt, KEY_LENGTH);
}

/**
 * @desc Encrypts a string using AES-256-GCM.
 * @param {string} text - The plaintext string to encrypt.
 * @returns {string} The base64 encoded encrypted string, including salt, IV, and auth tag.
 */
export function encrypt(text: string): string {
  if (!process.env.TOKEN_ENCRYPTION_KEY) {
    throw new Error("TOKEN_ENCRYPTION_KEY must be defined in the environment");
  }

  const salt = crypto.randomBytes(SALT_LENGTH);
  const iv = crypto.randomBytes(IV_LENGTH);
  const key = getKey(process.env.TOKEN_ENCRYPTION_KEY, salt);

  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  const encrypted = Buffer.concat([
    cipher.update(text, "utf8"),
    cipher.final(),
  ]);
  const tag = cipher.getAuthTag();

  return Buffer.concat([salt, iv, tag, encrypted]).toString("base64");
}

/**
 * @desc Decrypts an encrypted string previously generated by the encrypt function.
 * @param {string} encData - The base64 encoded string containing salt, IV, auth tag, and ciphertext.
 * @returns {string} The decrypted plaintext string.
 */
export function decrypt(encData: string): string {
  if (!process.env.TOKEN_ENCRYPTION_KEY) {
    throw new Error("TOKEN_ENCRYPTION_KEY must be defined in the environment");
  }

  const data = Buffer.from(encData, "base64");

  const salt = data.subarray(0, SALT_LENGTH);
  const iv = data.subarray(SALT_LENGTH, SALT_LENGTH + IV_LENGTH);
  const tag = data.subarray(
    SALT_LENGTH + IV_LENGTH,
    SALT_LENGTH + IV_LENGTH + TAG_LENGTH,
  );
  const text = data.subarray(SALT_LENGTH + IV_LENGTH + TAG_LENGTH);

  const key = getKey(process.env.TOKEN_ENCRYPTION_KEY, salt);
  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(tag);

  return decipher.update(text) + decipher.final("utf8");
}
