"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";

import _resource_card from "./resource-card.bones.json";
import _project_card from "./project-card.bones.json";
import _project_list_card from "./project-list-card.bones.json";
import _search_result from "./search-result.bones.json";
import _profile_metrics from "./profile-metrics.bones.json";

registerBones({
  "resource-card": _resource_card,
  "project-card": _project_card,
  "project-list-card": _project_list_card,
  "search-result": _search_result,
  "profile-metrics": _profile_metrics,
});
